### ISSUE TITLE
Battery drain

### ISSUE THREAD

**Issue by ktb92677** [mikeeq/mbp-fedora#14]
So I have been using Fedora on my Mac for a day now and it might be the placebo effect... but I feel like my battery has been dying really REALLY quickly. I mostly used my Mac for some coding and I used the same editor and web browser on both MacOSX and Fedora (Google Chrome, and Atom) and on Fedora I feel like the battery life is half as long as it was on MacOSX.

Has anyone else noticed this? Is there anything that can be done about this?

**Comment by mikeeq** [comment]
I was pretty sure that i responded you in that issues...

I recommend switching from `Atom` to `VS code,` because it consumes a lot fewer resources than `Atom`. You can use `powertop` to check what exactly consumes energy and optimize those services. You can also force CPU to work on lower frequencies which also should gain you some more battery time.

https://extensions.gnome.org/extension/945/cpu-power-manager/

**Comment by ktb92677** [comment]
Okay thank you very much!
