### ISSUE TITLE
How do I extract the release .zip and .z01 into an .iso?

### ISSUE THREAD

**Issue by jasonhan-vassar** [mikeeq/mbp-fedora#28]
Hi, what is the way to obtain the full .iso from the release files? I believe they are multipart but I'm not sure how to combine them into a single zip that `unzip` or my archive program can recognize. Can you please let me know the full command(s) to use? Thanks!

**Comment by guest-08** [comment]
Two ways but all have the same requirement: the livecd.zip and livecd.z01 need to be in the same folder.

**1 - The Unarchiver**
- Right click on any on the files
- Open with The Unarchiver

As long as they are in the same folder, it will be able to join them together automatically. 

**2 - Terminal**
- Open Terminal
The commands will look like this:
```
cd LOCATION_OF_FOLDER
cat file.z0N file.zip > name_of_unsplit_file.zip
unzip name_of_unsplit_file.zip
```

So, for me:
```
cd Downloads
cat livecd.z01 livecd.zip > livecd_unsplit.zip
unzip livecd_unsplit.zip
```

Cheers

**Comment by mikeeq** [comment]
Guys please... 

Everything is in a readme ;) 

- Download .iso from releases section - <https://github.com/mikeeq/mbp-fedora/releases/latest>
  - If it's splitted into multiple zip parts, you need to join splitted files into one and then extract it via `unzip` or extract them directly via `7z x` or `7za x`
    - <https://unix.stackexchange.com/questions/40480/how-to-unzip-a-multipart-spanned-zip-on-linux>
- Burn the image on USB stick >=8GB via:
  - dd - `dd bs=4M if=/home/user/Downloads/livecd-fedora-mbp-201908181858.iso of=/dev/sdc conv=fdatasync status=progress`
  - rufus (GPT)- <https://rufus.ie/>
  - fedora media writer (custom image option)- <https://getfedora.org/en/workstation/download/>
  - don't use `livecd-iso-to-disk`, because it's overwriting grub settings

**Comment by mikeeq** [comment]
If you will have any problems with booting the latest version from releases try v5.6.7-f32 release, it was built without DP patch.

**Comment by jasonhan-vassar** [comment]
Thank you!
