### ISSUE TITLE
Need Help?

### ISSUE THREAD

**Issue by duncanfinney** [mikeeq/mbp-fedora#3]
This project is really cool. Do you have anything that you'd like some help with?

**Comment by mikeeq** [comment]
Hi @duncanfinney, thanks for those kind words.

If you have some free time you can try to debug why kernel 5.2 is crashing so often during boot. 
https://github.com/mikeeq/mbp-fedora-kernel/releases/tag/v5.2.11-1

and pulseaudio config file is not perfect. You can try to enable dynamic audio input/output change triggered by plugging headphones to minijack or debug if microphone boost/volume is setup'ed correctly, because it sounds very quiet.
