### ISSUE TITLE
Macbook Air Wifi

### ISSUE THREAD

**Issue by ktb92677** [mikeeq/mbp-fedora#8]
Hi! So the installation on my 2019 Macbook Air went pretty well. I am having a bit of trouble getting the wifi driver to work. Here is what I did:

From MacOS:
ioreg -l | grep RequestedFiles
C-4355__s-C1/hawaii.trx, C-4355__s-C1/hawaii-X0.clmb, C-4355__s-C1/P-hawaii-X0_M-YSBC_V-u__m-4.3.txt

... So I copied these files and I installed fedora.

From Fedora:

I pasted these files as such:

C-4355__s-C1/hawaii.trx -> /lib/firmware/brcm/brcmfmac4355-pcie.bin
C-4355__s-C1/hawaii-X0.clmb -> /lib/firmware/brcm/brcmfmac4355-pcie.clm_blob
C-4355__s-C1/P-hawaii-X0_M-YSBC_V-u__m-4.3.txt -> "/lib/firmware/brcm/brcmfmac4355-pcie.Apple Inc.-MacBookAir8,2.txt"

I definitely did not make any typos when I plugged this in. The wifi does not come online. Any assistance would be greatly appreciated!

**Comment by ktb92677** [comment]
@mikeeq So per this comment: https://github.com/Dunedan/mbp-2016-linux/issues/112#issuecomment-523483504 looks like brcmfmac4355 is loading okay with at least one version of the kernel patch... is this fedora distribution using that patch?

**Comment by JohnQMetro** [comment]
@ktb92677 to me, your filenames look fine. I am not an expert, for me, fixing the filenames just allowed the computer to boot. Wifi did not work, but poking at things with command line utilities like iw (included in the iso), showed that the wifi was usable, there was some sort of config issue (probably due to the wifi not working during install). For now, I just use 'systemctl restart NetworkManager.service' after I log in to get the wifi working.
